### ISSUE TITLE
re-use 2015 email for topic overview 

### ISSUE THREAD

**Issue by gbinal** [18F/third-party-services#1]
@konklone - You wrote up a great summary of this issue in an April 2015 email to the content managers listserve.  Any problem if I tidy it up and reuse it's body as an artifact in this repo?  It won't be used as an end-all, be all but rather will just be a useful summary we can use in the interim.

**Comment by gbinal** [comment]
p.s.  I'll hold, pending your response.

**Comment by konklone** [comment]
Ah yeah, please - but please run the tidied up version by me in Slack or another venue first.

**Comment by gbinal** [comment]
Roger that .  Danke schön
