### ISSUE TITLE
Change the title in the pie chart 

### ISSUE THREAD

**Issue by smarina04** [18F/third-party-services#4]
Change "Participate in the Digital Analytics Program" title in the mockup to "Use Web-based Customer Satisfaction Surveys"

**Comment by gbinal** [comment]
Moving this over to [an issue in the `Pulse` repo](https://github.com/18F/pulse/issues/656) to assemble feedback for the next version of mockups.  

@smarina04 - can you use that issue to post any other changes you'd like for the next round of mockups?  

I'll go ahead and close this issue in the meantime.
